services:
  - type: web
    name: important-flowers
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /ImportantFlowers.html 